model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/qwen3-14b-fp8
      api_base: http://localhost:8000
      api_key: os.environ/VLLM_API_KEY

  - model_name: whisper-large-v3-turbo
    litellm_params:
      model: openai/whisper-large-v3-turbo
      api_base: http://localhost:8004
      api_key: os.environ/VLLM_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: false

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
